# -*- coding: utf-8 -*-
"""Sarcasm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KC9F5bHHZCtEYuPLTYrVCnsb2saMOvRR
"""

import pandas as pd
import re

from google.colab import files
uploaded = files.upload()

def clean_text(text):

    text = str(text).lower()

    text = re.sub(r'http\S+|www\S+', '', text)

    text = re.sub(r'@\w+', '', text)

    text = re.sub(r'\s+', ' ', text)

    text = text.strip()

    return text


df["TEXT"] = df["TEXT"].apply(clean_text)

df.head()

df["LABEL"] = df["LABEL"].map({
    "sarcastic": 1,
    "non-sarcastic": 0
})

df.head()

df.to_csv("clean_dataset.csv", index=False)

from google.colab import files
files.download("clean_dataset.csv")

from sklearn.model_selection import train_test_split

X = df["TEXT"]     # comments
y = df["LABEL"]    # sarcastic / non-sarcastic labels

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(df["TEXT"])

y = df["LABEL"]

print(X.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
matrix = confusion_matrix(y_test, y_pred)

with open("logistic_regression_results.txt", "w") as f:
    f.write("Logistic Regression Results\n\n")
    f.write(f"Accuracy: {accuracy}\n\n")
    f.write("Classification Report:\n")
    f.write(report)
    f.write("\nConfusion Matrix:\n")
    f.write(str(matrix))

print("Results saved successfully!")

from google.colab import files
files.download("logistic_regression_results.txt")

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

rf_model = RandomForestClassifier(n_estimators=200, random_state=42)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

accuracy_rf = accuracy_score(y_test, y_pred_rf)

print("Random Forest Accuracy:", accuracy_rf)
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

with open("random_forest_results.txt", "w") as f:
    f.write("Random Forest Results\n\n")
    f.write(f"Accuracy: {accuracy_rf}\n\n")
    f.write("Classification Report:\n")
    f.write(classification_report(y_test, y_pred_rf))
    f.write("\nConfusion Matrix:\n")
    f.write(str(confusion_matrix(y_test, y_pred_rf)))

print("Random Forest results saved!")

from google.colab import files
files.download("random_forest_results.txt")

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

svm_model = LinearSVC()

svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

accuracy_svm = accuracy_score(y_test, y_pred_svm)

print("SVM Accuracy:", accuracy_svm)
print("\nClassification Report:\n", classification_report(y_test, y_pred_svm))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))

with open("svm_results.txt", "w") as f:
    f.write("SVM Results\n\n")
    f.write(f"Accuracy: {accuracy_svm}\n\n")
    f.write("Classification Report:\n")
    f.write(classification_report(y_test, y_pred_svm))
    f.write("\nConfusion Matrix:\n")
    f.write(str(confusion_matrix(y_test, y_pred_svm)))

print("SVM results saved!")

from google.colab import files
files.download("svm_results.txt")

from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    stratify=df["LABEL"],
    random_state=42
)

print(train_df.shape)
print(test_df.shape)

train_texts = train_df["TEXT"].tolist()
test_texts = test_df["TEXT"].tolist()

train_labels = train_df["LABEL"].tolist()
test_labels = test_df["LABEL"].tolist()

print("Training samples:", len(train_texts))
print("Testing samples:", len(test_texts))

!pip install transformers datasets accelerate -q

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-multilingual-cased")

print("Tokenizer loaded successfully")

df = pd.read_excel("DATASET.csv.xlsx")

df.head()

def tokenize_function(example):
    return tokenizer(
        example['text'],
        padding='max_length',
        truncation=True,
        max_length=128
    )

# STEP 4: Convert to dataset + tokenize

from datasets import Dataset

# Fix column names (important)
df.columns = df.columns.str.strip()
df = df.rename(columns={
    'TEXT': 'text',
    'LABEL': 'label'
})

print("Columns:", df.columns)

# Convert to HuggingFace dataset
dataset = Dataset.from_pandas(df)

# Apply tokenization
tokenized_dataset = dataset.map(tokenize_function, batched=True)

# Remove unnecessary columns
tokenized_dataset = tokenized_dataset.remove_columns(['text'])

# Rename label column
tokenized_dataset = tokenized_dataset.rename_column("label", "labels")

# Remove ID if present
if 'ID' in tokenized_dataset.column_names:
    tokenized_dataset = tokenized_dataset.remove_columns(['ID'])

# Set format
tokenized_dataset.set_format("torch")

# Preview
print(tokenized_dataset)

train_test_split = tokenized_dataset.train_test_split(test_size=0.2)

train_dataset = train_test_split['train']
test_dataset = train_test_split['test']

print("Train size:", len(train_dataset))
print("Test size:", len(test_dataset))

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-multilingual-cased",
    num_labels=2   # 0 = non-sarcastic, 1 = sarcastic
)

print("Model loaded successfully!")

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    do_train=True,
    do_eval=True,
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=4,
    weight_decay=0.01
)

# STEP 8: Trainer + Training

from transformers import Trainer
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# 🔹 Evaluation metrics
def compute_metrics(pred):
    logits, labels = pred
    predictions = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, predictions, average='binary'
    )
    acc = accuracy_score(labels, predictions)

    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

# 🔹 Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

# 🔹 Start training
trainer.train()

# STEP 9: Final Evaluation

results = trainer.evaluate()

print("Final Evaluation Results:")
print(results)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Get predictions
predictions = trainer.predict(test_dataset)
y_pred = predictions.predictions.argmax(axis=1)
y_true = predictions.label_ids

# Confusion matrix
cm = confusion_matrix(y_true, y_pred)

# Plot
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.show()

# Normal Confusion Matrix (numbers)

from sklearn.metrics import confusion_matrix

# Get predictions
predictions = trainer.predict(test_dataset)
y_pred = predictions.predictions.argmax(axis=1)
y_true = predictions.label_ids

# Confusion matrix
cm = confusion_matrix(y_true, y_pred)

print("Confusion Matrix:")
print(cm)

